# Generated by Django 6.0.3 on 2026-03-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('cerveza', 'Cerveza'), ('licor', 'Licor'), ('cigarrillo', 'Cigarrillos')], max_length=30)),
                ('stock', models.IntegerField()),
                ('precio_uni', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='ProductoApp')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
